automation:
    - id: 'child1_bedroom_good_morning'
      alias: child1 Bedroom - Good Morning
      description: ''
      trigger:
      - platform: time
        at: 07:10
      condition:
      - condition: state
        entity_id: input_boolean.school_holidays
        state: "off"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      action:
      - device_id: 93f924d517b311ebb9bb8d79d0cf841c
        domain: cover
        entity_id: cover.velux_internal_cover_4
        type: set_position
        position: 100
      - delay: 01:05:00
      - service: light.turn_off
        target:
          entity_id: 
            - light.bedroom_1_bedside_lamp
      mode: single
    - id: 'child1_bedroom_good_morning_left_for_school'
      alias: child1 Bedroom - Good Morning - Left for school
      description: ''
      trigger:
      - platform: time
        at: 09:00
      condition:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      action:
      - service: switch.turn_off
        target:
          entity_id: 
            - switch.bedroom_1_light_relay_0
      mode: single      
    - id: 'child1_bedroom_good_morning_weekend'
      alias: child1 Bedroom - Good Morning - Weekend
      description: ''
      trigger:
      - platform: time
        at: 09:00
      condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "on"
          - condition: time
            weekday:
            - sat
            - sun
      action:
      - device_id: 93f924d517b311ebb9bb8d79d0cf841c
        domain: cover
        entity_id: cover.velux_internal_cover_4
        type: set_position
        position: 100
      - delay: 00:00:20
      - service: light.turn_off
        target:
          entity_id:
            - light.bedroom_1_bedside_lamp
      mode: single
    - id: 'child1_bedroom_good_night'
      alias: child1 Bedroom - Good Night
      description: ''
      trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: -2.5
      - platform: time
        at: '19:00'
      condition: []
      action:
      - service: light.turn_on
        target:
          entity_id:
            - light.bedroom_1_bedside_lamp
      - device_id: 93f924d517b311ebb9bb8d79d0cf841c
        domain: cover
        entity_id: cover.velux_internal_cover_4
        type: set_position
        position: 0
      mode: single

