automation:
  - id: "bedroom1_good_morning"
    alias: Bedroom 1 - Good Morning
    description: ""
    mode: single
    trigger:
      - platform: time
        at: 07:10
    condition:
      - condition: numeric_state
        entity_id: sensor.downstairs_hall_smoke_alarm_temperature
        below: 21.5
      - condition: state
        entity_id: input_boolean.school_holidays
        state: "off"
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: script.turn_on
        entity_id: script.bedroom1_blind_open
      - delay: 01:05:00
      - service: light.turn_off
        target:
          entity_id:
            - light.bedroom_1_bedside_lamp_local
  - id: "bedroom1_good_morning_left_for_school"
    alias: Bedroom 1 - Good Morning - Left for school
    description: ""
    mode: single
    trigger:
      - platform: time
        at: 09:00
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.bedroom_1_light_relay_0
  - id: "bedroom1_good_morning_weekend"
    alias: Bedroom 1 - Good Morning - Weekend
    description: ""
    mode: single
    trigger:
      - platform: time
        at: 09:00
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "on"
          - condition: time
            weekday:
              - sat
              - sun
    action:
      - service: script.turn_on
        entity_id: script.bedroom1_good_morning
  - id: "bedroom1_good_night"
    alias: Bedroom 1 - Good Night
    description: ""
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: -2.5
      - platform: time
        at: "20:30"
    condition: []
    action:
      - service: script.turn_on
        entity_id: script.bedroom1_good_night
