automation:
    - id: 'child1_bedroom_wake_up_reminder'
      alias: child1 Bedroom - Wake Up Reminder
      description: ''
      trigger:
      - platform: time
        at: 07:12:00
      condition:
      - condition: state
        entity_id: input_boolean.school_holidays
        state: "off"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.child1s_room
          volume_level: 0.5
      - service: notify.alexa_media
        data:
          message: child1, its time to get up for school.  Dont forget to put on deodorant
          data:
            type: tts
          target:
          - media_player.child1s_room
      mode: single
    - id: 'child1_bedroom_leave_reminder'
      alias: child1 Bedroom - Leave Reminder
      description: ''
      trigger:
      - platform: time
        at: 08:00:00
      condition:
      - condition: state
        entity_id: input_boolean.school_holidays
        state: "off"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.child1s_room
          volume_level: 0.5
      - service: notify.alexa_media
        data:
          message: child1, you've got ten minutes before your friends arrive, are you ready ?
          data:
            type: tts
          target:
          - media_player.child1s_room
      mode: single