automation:
  - id: back_door_open
    alias: "Back door open"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.back_door_contact_sensor
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0
    condition: []
    action:
      - service: notify.family
        data:
          message: The back door is open, go check it
          data:
            sticky: "true"
