automation:
- id: back_door_open
  alias: "Back door open"
  trigger:
    platform: state
    entity_id: binary_sensor.downstairs_hall_back_door_sensor_status
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.family
    data:
      message: The back door is open, go check it
  mode: single
