automation:
  - id: upstairs_bathroom_motion_light
    alias: Upstairs Bathroom - Motion Light
    description: ""
    mode: restart
    max_exceeded: silent
    trigger:
      platform: state
      entity_id: binary_sensor.upstairs_bathroom_motion_sensor_motion
      to: "off"
      for: "00:10:00"
    action:
      - service: light.turn_off
        target:
          entity_id: light.upstairs_bathroom_light
