automation:
    - id: 'tado_monitoring'
      alias: Heating - Monitoring
      description: ''
      trigger:
      - platform: state
        entity_id: climate.heating
        to: unavailable
        for: 00:05:00
      condition: []
      action:
      - service: notify.mobile_app_mobile_dad
        data:
          message: Tado is unresponsive
      mode: single
