automation:
    - id: 'tado_arrive'
      alias: Heating - Arrive
      description: ''
      trigger:
      - platform: state
        entity_id: group.people
        from: not_home
        to: home
      condition: []
      action:
      - device_id: 0fa5fbc01b9911ebb57d7bea9876cb88
        domain: climate
        entity_id: climate.heating
        type: set_preset_mode
        preset_mode: home
      mode: single
