
homeassistant:
  packages: !include_dir_named packages
  currency: GBP

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:



logger:
  default: warning
#  default: info
  logs:
    custom_components.reolink_dev: debug
    custom_components.reolink_dev.base.data: warning
    reolink: debug
#  default: critical
#  logs:
#    custom_components.entity_controller: debug
#    pyhap: debug
#    homeassistant.components.python_script: debug
#    homeassistant.components.automation: info
#    homeassistant.components.homekit: debug
#    homeassistant.components.automation: debug
#    homeassistant.components.rest.sensor: debug
#    homeassistant.components.rest_command: debug
#    homeassistant.components.binary_sensor: debug
    
cloud:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  configurator:
    title: File Editor
    icon: mdi:wrench
    url: !secret url_file_editor
  vscode:
    title: VSCode
    icon: mdi:wrench
    url: http://ha.home:8888

python_script:

recorder:
  exclude:
    entity_globs:
      - sensor.4g*
      - sensor.adsl*
      - main_bedroom_dads_bedside_lamp*
    entities:
      - binary_sensor.bedroom1_noise_sensor
