
homeassistant:
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: info
  logs:
    homeassistant.components.automation: debug
#    homeassistant.components.rest.sensor: debug
#    homeassistant.components.rest_command: debug
#    homeassistant.components.binary_sensor: debug
    
cloud:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  configurator:
    title: File Editor
    icon: mdi:wrench
    url: http://wopr.home:3218

#switch:
#- platform: template
#  switches: !include_dir_merge_named switches

timer:
  vacuum:
    duration: '00:30:00'
    
