
homeassistant:
  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: info
  logs:
#    pyhap: debug
    homeassistant.components.python_script: debug
    homeassistant.components.automation: info
#    homeassistant.components.homekit: debug
#    homeassistant.components.automation: debug
#    homeassistant.components.rest.sensor: debug
#    homeassistant.components.rest_command: debug
#    homeassistant.components.binary_sensor: debug
    
cloud:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_iframe:
  configurator:
    title: File Editor
    icon: mdi:wrench
    url: !secret url_file_editor

python_script:
