automation:
  - id: "front_hot_tub_school"
    alias: Front - Hot Tub - School
    description: ""
    trigger:
      - platform: time
        at: 06:30:00
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
      - condition: state
        entity_id: binary_sensor.spa_connected
        state: "true"
      - condition: numeric_state
        entity_id: sensor.otley_probability_of_precipitation
        below: 80
    action:
      - service: climate.set_temperature
        target:
          entity_id: climate.spa_thermostat
        data:
          temperature: 20
    mode: single
