automation:
  - id: "front_hottub_good_night"
    alias: Front - Hot Tub - Good Night
    description: ""
    trigger:
      - platform: time
        at: "18:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: state
        entity_id: binary_sensor.spa_connected
        state: "on"
    action:
      - service: rest_command.hottub_temp_set
        data:
          hottub_water_target: 20
    mode: single
