automation:
  - id: "front_hot_tub_filter_cycles"
    alias: Front - Hot Tub - Filter Cycles
    description: ""
    trigger:
      - platform: time
        at: "06:00:00"
      - platform: time
        at: "18:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: state
        entity_id: binary_sensor.spa_connected
        state: "true"
    action:
      - service: switch.turn_on
        entity_id: switch.spa_filter
      - delay: "02:00:00"
      - service: switch.turn_off
        entity_id: switch.spa_filter
    mode: single
