automation:
    - id: 'front_hottub_good_night'
      alias: Front - Hot Tub - Good Night
      description: ''
      trigger:
      - platform: time
        at: '18:00:00'
      condition:
      - condition: state
        entity_id: sensor.hottub_online
        state: 'true'
      action:
      - service: rest_command.hottub_temp_set
        data:
          hottub_water_target: 30
      mode: single
