automation:
  - id: "front_hottub_weekend"
    alias: Front - Hot Tub - Weekend
    description: ""
    trigger:
      - platform: time
        at: 05:00:00
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: time
        weekday:
          - sat
          - sun
      - condition: state
        entity_id: binary_sensor.spa_connected
        state: "true"
    action:
      - service: climate.set_temperature
        target:
          entity_id: climate.spa_thermostat
        data:
          temperature: 20
    mode: single
