automation:
  - id: "bedroom2_pc_wake"
    alias: Bedroom 2 - Laptop - Wake
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.bedroom_2_laptop_options
        to: Wake
    condition: []
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: e4:5e:37:a9:b6:f4
      - delay: "2"
      - service: input_select.select_option
        data:
          option: None
        entity_id: input_select.bedroom_2_laptop_options
    mode: single
  - id: "bedroom2_pc_sleep"
    alias: Bedroom 2 - Laptop - Sleep
    description: ""
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "off"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
    trigger:
      - platform: state
        entity_id: input_select.bedroom_2_laptop_options
        to: Sleep
      - platform: time
        at: "21:00:00"
#    condition:
#      - condition: state
#        entity_id: sensor.bedroom_2_laptop_sessionstate
#        state: 
#          - "Unlocked"
#          - "Locked"
    action:
      - service: button.press
        target:
          entity_id: button.bedroom_2_laptop_sleep
      - delay: "2"
      - service: input_select.select_option
        data:
          option: None
        entity_id: input_select.bedroom_2_laptop_options
    mode: single
