automation:
  - id: "bedroom2_xbox_off"
    alias: Bedroom 2 - Xbox - Off
    description: ""
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "off"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
    trigger:
      - platform: time
        at: "21:00:00"
    action:
      - service: media_player.turn_off
        data: {}
        entity_id: media_player.xbox_bedroom_2
    mode: single
