automation:
  - id: bedroom_2_motion_light
    alias: Bedroom 2 - Motion Light
    description: ''
    mode: restart
    max_exceeded: silent
    condition:
      - condition: sun
        after: sunset
        after_offset: "-00:30:00"
      - condition: time
        before: "19:00:00"
    trigger:
      platform: state
      entity_id: binary_sensor.bedroom_2_motion_sensor_motion
      from: 'off'
      to: 'on'
    action:
      - service: light.turn_on
        target:
          entity_id: light.bedroom2_light
      - wait_for_trigger:
          platform: state
          entity_id: binary_sensor.bedroom_2_motion_sensor_motion
          from: 'on'
          to: 'off'
      - delay: 600
      - service: light.turn_off
        target:
          entity_id: light.bedroom2_light
