automation:
    - id: 'child2_bedroom_good_morning'
      alias: child2 Bedroom - Good Morning
      description: ''
      trigger:
      - platform: time
        at: 07:50
      condition:
      - condition: state
        entity_id: input_boolean.school_holidays
        state: "off"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      action:
      - service: cover.open_cover
        entity_id: cover.bedroom_2
#        entity_id: cover.velux_internal_cover_5
      - delay: 00:40:00
      - service: light.turn_off
        target:
          entity_id:
            - light.bedroom_2_bedside_lamp
      mode: single
    - id: 'child2_bedroom_good_morning_weekend'
      alias: child2 Bedroom - Good Morning - Weekend
      description: ''
      mode: single
      trigger:
      - platform: time
        at: 09:00
      condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "on"
          - condition: time
            weekday:
            - sat
            - sun
      action:
      - service: script.turn_on
        entity_id: script.bedroom2_good_morning
    - id: 'child2_bedroom_good_morning_left_for_school'
      alias: child2 Bedroom - Good Morning - Left for school
      description: ''
      trigger:
      - platform: time
        at: 09:00
      condition:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      action:
      - service: switch.turn_off
        target:
          entity_id: 
            - switch.bedroom_2_light_relay_0
      mode: single  
    - id: 'child2_bedroom_good_night'
      alias: child2 Bedroom - Good Night
      description: ''
      mode: single
      trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: -2.5
      - platform: time
        at: '19:00'
      condition: []
      action:
      - service: script.turn_on
        entity_id: script.bedroom2_good_night
