automation:
  - id: "bedroom_2_led_sign_on"
    alias: Bedroom2 - LED Sign On
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.xbox_bedroom_2
        from: "off"
        to: "playing"
      - platform: state
        entity_id: sensor.bedroom_2_laptop_sessionstate
        from: "unavailable"
    condition: []
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.bedroom_2_led_sign
    mode: single
  - id: "bedroom_2_led_sign_off"
    alias: Bedroom2 - LED Sign Off
    description: ""
    trigger:
      - platform: state
        entity_id: media_player.xbox_bedroom_2
        from: "playing"
        to: "off"
      - platform: state
        entity_id: sensor.bedroom_2_laptop_sessionstate
        to: "unavailable"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.xbox_bedroom_2
          state: "off"
        - condition: state
          entity_id: sensor.bedroom_2_laptop_sessionstate
          state: "unavailable"
    action:
      - service: light.turn_off
        target:
          entity_id:
            - light.bedroom_2_led_sign
    mode: single
