automation:
  - id: automation_main_bedroom_tv_state_on
    alias: Main Bedroom - TV - State On
    description: "Sets the boolean status of the TV to on"
    mode: single
    trigger:
      - platform: state
        entity_id: media_player.master_bedroom_tv
        from: "off"
        to: "on"
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.main_bedroom_tv_switch
  - id: automation_main_bedroom_tv_state_off
    alias: Main Bedroom - TV - State Off
    description: "Sets the boolean status of the TV to off"
    mode: single
    trigger:
      - platform: state
        entity_id: media_player.master_bedroom_tv
        from: "on"
        to: "off"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.main_bedroom_tv_switch
