automation:
    - id: 'blink_disarm_scheduled'
      alias: Blink - Disarm - Scheduled
      description: ''
      trigger:
      - platform: sun
        event: sunrise
        offset: -01:00:00
      condition: 
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      action:
      - service: alarm_control_panel.alarm_disarm
        data: {}
        entity_id: alarm_control_panel.blink_home
      mode: single
