automation:
    - id: 'blink_arm_presence'
      alias: Blink - Arm - Presence
      description: ''
      trigger:
      - platform: state
        entity_id: group.people
        to: not_home
        from: home
      condition: []
      action:
      - service: alarm_control_panel.alarm_arm_away
        data: {}
        entity_id: alarm_control_panel.blink_home
      mode: single
