automation:
  - id: 'blink_trigger_camera_snapshot'
    alias: Blink - Trigger Snapshot
    description: ''
    mode: single
    trigger:
    - at: '10:00:00'
      platform: time
    condition: []
    action:
      - service: blink.trigger_camera
        target:
          entity_id:
            - camera.blink_kitchen_camera
      - delay: "00:00:15"
      - service: blink.trigger_camera
        target:
          entity_id:
            - camera.blink_lounge_camera
      - delay: "00:00:15"
      - service: blink.trigger_camera
        target:
          entity_id:
            - camera.blink_front_camera
      - delay: "00:00:15"
      - service: blink.trigger_camera
        target:
          entity_id:
            - camera.blink_back_camera
