automation:
    - id: 'blink_arm_scheduled'
      alias: Blink - Arm - Scheduled
      description: ''
      trigger:
      - platform: time
        at: '22:00:00'
      condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      action:
      - service: alarm_control_panel.alarm_arm_away
        data: {}
        entity_id: alarm_control_panel.blink_home
      mode: single
