automation:
  - id: "study_power_socket_on"
    alias: Study - Power Socket On
    description: ""
    trigger:
      - platform: time
        at: 06:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.study_power_socket_on_off
    mode: single
  - id: "study_power_socket_off"
    alias: Study - Power Socket Off
    description: ""
    trigger:
      - platform: time
        at: "00:00"
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.study_power_socket_on_off
    mode: single
