automation:
  - id: "study_good_night"
    alias: Study - Good Night
    description: ""
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        below: -2.5
      - platform: time
        at: "20:30"
    condition: []
    action:
      - service: cover.close_cover
        entity_id: cover.studyblind_2
#      - service: script.turn_on
#        entity_id: script.study_good_night