automation:
    - id: 'study_oil_radiator_on'
      alias: Study - Oil Radiator On
      description: ''
      trigger:
      - platform: time
        at: 09:00
      condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      action:
      - service: switch.turn_on
        target:
          entity_id: 
            - switch.study_oil_radiator
      mode: single
    - id: 'study_oil_radiator_off'
      alias: Study - Oil Radiator Off
      description: ''
      trigger:
      - platform: time
        at: '15:00'
      condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      action:
      - service: switch.turn_off
        target:
          entity_id: 
            - switch.study_oil_radiator
      mode: single
