binary_sensor:
  - platform: ffmpeg_noise
    name: "Bedroom1 noise sensor"
    input: !secret bedroom1_noise_sensor_input
    initial_state: true
    extra_arguments: -nostats
    duration: 1
    reset: 5
    peak: -27
