automation:
  - alias: Anniversary Automation
    trigger:
      - platform: state
        entity_id:
          - sensor.anniversary_birthday_grandma
          - sensor.anniversary_birthday_grandad
        to: "7"
    action:
      - service: notify.dad
        data:
          message: "{{trigger.to_state.attributes.friendly_name}}'s Birthday is in a week !"
