automation:
  - id: "energy_saving"
    alias: Energy Saving
    description: ""
    mode: single
    trigger:
      - platform: time
        at: 08:59
    condition:
      - condition: state
        entity_id: input_boolean.school_holidays
        state: "off"
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: light.turn_off
        target:
          entity_id:
            - light.bedroom_1_light
            - light.bedroom2_light
            - light.bedroom_1_bedside_lamp
            - light.bedroom_2_bedside_lamp
      - service: media_player.turn_off
        target:
          entity_id:
            - media_player.xbox_bedroom_1
            - media_player.xbox_bedroom_2
            - media_player.xbox_lounge
            - media_player.xbox_lounge_window
      - service: remote.turn_off
        data: {}
        target:
          entity_id: remote.lounge
