automation:
    - id: 'energy_saving'
      alias: Energy Saving
      description: ''
      mode: single
      trigger:
      - platform: time
        at: 09:00
      condition:
      - condition: state
        entity_id: input_boolean.school_holidays
        state: "off"
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      action:
      - service: light.turn_off
        target:
          entity_id:
            - light.main_bedroom_light
            - light.bedroom_1_light
            - light.bedroom_2_light
            - light.bedroom_1_bedside_lamp
            - light.bedroom_2_bedside_lamp
      - service: media_player.turn_off
        target:
          entity_id:
            - media_player.master_bedroom_skyq
            - media_player.xbox_spareroom
            - media_player.xbox_child2
      - service: remote.turn_off
        data: {}
        target:
          entity_id: remote.lounge

