automation:
  - id: "arrive_home"
    alias: Presence - Arrive Home
    description: ""
    trigger:
      - platform: state
        entity_id: group.people
        from: not_home
        to: home
    condition: []
    action:
      - device_id: 0fa5fbc01b9911ebb57d7bea9876cb88
        domain: climate
        entity_id: climate.lounge
        type: set_preset_mode
        preset_mode: home
      - service: light.turn_on
        target:
          entity_id:
            - light.downstairs_hall_lamp_level_light_color_on_off
#      - service: switch.turn_on
#        target:
#          entity_id:
#            - switch.reolink_lounge_recording
#            - switch.reolink_kitchen_recording
    mode: single
  - id: "leave_home"
    alias: Presence - Leave Home
    description: ""
    trigger:
      - platform: state
        entity_id: group.people
        from: home
        to: not_home
    condition: []
    action:
      - device_id: 0fa5fbc01b9911ebb57d7bea9876cb88
        domain: climate
        entity_id: climate.lounge
        type: set_preset_mode
        preset_mode: away
      - service: light.turn_off
        target:
          entity_id:
            - light.downstairs_hall_lamp_level_light_color_on_off
#      - service: switch.turn_off
#        target:
#          entity_id:
#            - switch.reolink_lounge_recording
#            - switch.reolink_kitchen_recording
    mode: single
  - id: "leave_home_ethan"
    alias: Presence - Leave Home Ethan
    description: ""
    trigger:
      - platform: state
        entity_id: person.ethan
        from: home
        to: not_home
    condition:
      - condition: state
        entity_id: "switch.bedroom1_laptop_hibernate"
        state: "unknown"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.bedroom_1_light_relay_0
      - service: switch.toggle
        target:
          entity_id: switch.bedroom1_laptop_hibernate
    mode: single
