automation:
  - id: "arrive_home"
    alias: Presence - Arrive Home
    description: ""
    trigger:
      - platform: state
        entity_id: group.people
        from: not_home
        to: home
    condition: []
    action:
      - device_id: 0fa5fbc01b9911ebb57d7bea9876cb88
        domain: climate
        entity_id: climate.lounge
        type: set_preset_mode
        preset_mode: home
      - service: light.turn_on
        target:
          entity_id:
            - light.downstairs_hall_lamp_level_light_color_on_off
      - service: switch.turn_off
        target:
          entity_id:
            - switch.lounge_camera_socket
    mode: single
  - id: "leave_home"
    alias: Presence - Leave Home
    description: ""
    trigger:
      - platform: state
        entity_id: group.people
        from: home
        to: not_home
    condition: []
    action:
      - device_id: 0fa5fbc01b9911ebb57d7bea9876cb88
        domain: climate
        entity_id: climate.lounge
        type: set_preset_mode
        preset_mode: away
      - service: light.turn_off
        target:
          entity_id:
            - light.downstairs_hall_lamp_level_light_color_on_off
      - service: switch.turn_on
        target:
          entity_id:
            - switch.lounge_camera_socket
    mode: single
  - id: "leave_home_ethan"
    alias: Presence - Leave Home Ethan
    description: ""
    trigger:
      - platform: state
        entity_id: person.ethan
        from: home
        to: not_home
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.bedroom_1_light_relay_0
      - service: button.press
        target:
          entity_id: button.bedroom_1_laptop_sleep
      - service: media_player.turn_off
        data: {}
        entity_id: media_player.xbox_bedroom_1
    mode: single
