automation:
    #############################################################################
    ## Turn on/off indoor lights randomly
    #############################################################################
    # https://community.home-assistant.io/t/holiday-vacation-mode/151426/4
    - id: 'On Holiday - Random Away Lights'
      alias: 'On Holiday - Random Away Lights'
      initial_state: True
    
      trigger:
        - platform: time_pattern
          minutes: '/30'
    
      condition:
        - condition: state
          entity_id: input_boolean.on_holiday
          state: 'on'
        - condition: sun
          after: sunset
          after_offset: '-00:30:00'
        - condition: time
          before: '22:00:00'
    
      action:
        - delay: "00:{{ '{:02}'.format(range(0,30) | random | int(0)) }}:00"
    
        # Selecting entity for toggling
        - service: input_text.set_value
          data_template:
            entity_id: input_text.light_to_switch
            value: "{{ state_attr('group.on_holiday_lights','entity_id') | random }}"
    
        # Toggling entity state
        - service: homeassistant.toggle
          data_template:
            entity_id: "{{states('input_text.light_to_switch')}}"
    
    ################################################################
    ## Stopping presence simulation randomly 22:30
    ################################################################
    - id: 'On Holiday - Turning off all toggled lights'
      alias: 'On Holiday - Turning off all toggled lights'
      initial_state: True
    
      trigger:
        - platform: time
          at: '22:30:00'
    
      condition:
        - condition: state
          entity_id: group.people
          state: 'not_home'

      action:
        - delay: '00:{{ range(15,59) | random | int(0) }}:00'
        - service: homeassistant.turn_off
          entity_id: group.on_holiday_lights

    - id: 'On Holiday - Turn off all house lights when toggled'
      alias: 'On Holiday - Turn off all house lights when toggled'
      
      trigger:
        - platform: state
          entity_id:
            - input_boolean.on_holiday
          from: "off"
          to: "on"
          
      action:
        - service: homeassistant.turn_off
          entity_id: group.lights



    - id: 'On Holiday - Set Away'
      alias: 'On Holiday - Set Away for heating, cameras and alarm'
      trigger:
        - platform: state
          entity_id:
            - input_boolean.on_holiday
          from: "off"
          to: "on"
      action:
        - service: climate.set_preset_mode
          data:
            preset_mode: away
          target:
            entity_id: climate.lounge
        - service: alarm_control_panel.alarm_arm_away
          target:
            entity_id: alarm_control_panel.alarmo
        - service: alarm_control_panel.alarm_arm_away
          target:
            entity_id: alarm_control_panel.blink_home

    - id: 'On Holiday - Set Home'
      alias: 'On Holiday - Set Home for heating, cameras and alarm'
      trigger:
        - platform: state
          entity_id:
            - input_boolean.on_holiday
          from: "on"
          to: "off"
      action:
        - service: climate.set_preset_mode
          data:
            preset_mode: home
          target:
            entity_id: climate.lounge
        - service: alarm_control_panel.alarm_disarm
          target:
            entity_id: alarm_control_panel.alarmo
        - service: alarm_control_panel.alarm_disarm
          target:
            entity_id: alarm_control_panel.blink_home

