# https://github.com/jazzyisj/unavailable-entities-sensor
# REQUIRED - This is the template sensor
template:
  - sensor:
      - name: "Unavailable Entities"
        unique_id: unavailable_entities
        icon: "{{ 'mdi:alert-circle' if states('sensor.unavailable_entities')|int(0) > 0 else 'mdi:check-circle' }}"
        unit_of_measurement: entities
        state: >
          {% if state_attr('sensor.unavailable_entities','entities') != none %}
            {{ state_attr('sensor.unavailable_entities','entities')|count }}
          {% endif %}
        attributes:
          entities: >
            {% set ignore_seconds = 60 %}
            {% set ignore_ts = (now().timestamp() - ignore_seconds)|as_datetime %}
            {{ states
              |rejectattr('domain','eq','group')
              |rejectattr('entity_id','in',state_attr('group.ignored_unavailable_entities','entity_id'))
              |rejectattr('last_changed','ge',ignore_ts)
              |selectattr('state','in',['unavailable','unknown','none'])|map(attribute='entity_id')|list }}

group:
  ignored_unavailable_entities:
    entities:
      - media_player.lg_webos_tv_d1bd
      - sensor.back_door_last_ding
      - binary_sensor.updater
      - sensor.dads_toothbrush
      - cover.bedroom
      - sensor.samsung_q60_series_lounge_media_playback_status
      - sensor.downstairs_bathroom_light_power_0
      - sensor.velux_sensor_current_temperature
      - sensor.downstairs_bathroom_motion_sensor_rssi
      - sensor.downstairs_bathroom_motion_sensor_ssid
      - sensor.downstairs_bathroom_motion_sensor_uptime
      - sensor.downstairs_bathroom_motion_sensor_ip
      - sensor.bedroom1_motion_sensor_rssi
      - sensor.bedroom1_motion_sensor_ssid
      - sensor.bedroom1_motion_sensor_uptime
      - sensor.bedroom1_motion_sensor_ip
      - binary_sensor.bedroom1_motion_sensor_charger
      - binary_sensor.downstairs_bathroom_motion_sensor_charger
      - sensor.deebot_ozmo_920_kitchen_last_clean_image
      - sensor.deebot_ozmo_920_kitchen_stats_area
      - sensor.deebot_ozmo_920_kitchen_stats_time
      - sensor.deebot_ozmo_920_kitchen_stats_type
      - sensor.deebot_ozmo_920_kitchen_water_level
      - sensor.deebot_ozmo_920_lounge_stats_area
      - sensor.deebot_ozmo_920_lounge_stats_time
      - sensor.deebot_ozmo_920_lounge_brush
      - sensor.deebot_ozmo_920_lounge_heap
      - sensor.deebot_ozmo_920_lounge_sidebrush
      - sensor.deebot_ozmo_920_lounge_stats_type
      - sensor.deebot_ozmo_920_lounge_water_level
      - sensor.deebot_ozmo_920_lounge_last_clean_image
      - binary_sensor.deebot_ozmo_920_lounge_mop_attached
      - sensor.deebot_ozmo_t8_aivi_kitchen_last_clean_image
      - sensor.deebot_ozmo_t8_aivi_kitchen_stats_area
      - sensor.deebot_ozmo_t8_aivi_kitchen_stats_time
      - sensor.deebot_ozmo_t8_aivi_kitchen_stats_type
      - sensor.deebot_ozmo_t8_aivi_kitchen_water_level
      - sensor.deebot_ozmo_t8_aivi_kitchen_brush
      - sensor.deebot_ozmo_t8_aivi_kitchen_heap
      - sensor.deebot_ozmo_t8_aivi_kitchen_sidebrush
      - binary_sensor.deebot_ozmo_t8_aivi_kitchen_mop_attached
      - button.deebot_ozmo_920_lounge_life_span_brush_reset
      - button.deebot_ozmo_920_lounge_life_span_filter_reset
      - button.deebot_ozmo_920_lounge_life_span_side_brush_reset
      - button.deebot_ozmo_t8_aivi_kitchen_life_span_brush_reset
      - button.deebot_ozmo_t8_aivi_kitchen_life_span_filter_reset
      - button.deebot_ozmo_t8_aivi_kitchen_life_span_side_brush_reset
      - sensor.libby_ble
      - sensor.bedroom_1_light_energy_0
      - sensor.bedroom_1_light_power_0
      - sensor.bedroom_2_light_energy_0
      - sensor.bedroom_2_light_power_0
      - button.lounge_lights_update_firmware
      - button.main_bedroom_lights_update_firmware
      - sensor.downstairs_bathroom_light_power_0
      - sensor.downstairs_bathroom_light_energy_0
      - sensor.hottub_error
      - sensor.hottub_online
      - sensor.hottub_pump_target
      - sensor.hottub_pump_temp
      - sensor.hottub_status
      - sensor.hottub_summary
      - sensor.hottub_water_temp
      - switch.hottub_bubbles
      - switch.hottub_filter
      - switch.hottub_heat
      - switch.hottub_power
      - sensor.lounge_lights_overpower_value_0
      - sensor.main_bedroom_lights_energy_0
      - sensor.main_bedroom_lights_power_0
      - button.bedroom1_lights_update_firmware
      - button.bedroom2_lights_update_firmware
      - button.curtains_my_position
      - sensor.homekit_setup_code
      - button.downstairs_bathroom_lights_update_firmware
      - binary_sensor.shelly_motion_60a423936d7e_charger
      - binary_sensor.shelly_motion_60a423936d7e_firmware_update
      - binary_sensor.shelly_motion_60a423936d7e_motion
      - binary_sensor.shelly_motion_60a423936d7e_vibration
      - sensor.shelly_motion_60a423936d7e_battery
      - sensor.shelly_motion_60a423936d7e_lux
      - sensor.lumi_lumi_remote_b1acn01_power
      - button.develco_zhemi101_8a19021b_identify
      - button.ewelink_ms01_d50e4e23_identify
      - button.lg_webos_tv_d1bd_identify
      - button.lumi_lumi_sensor_magnet_aq2_5c11bc07_identify
      - button.lumi_lumi_sensor_motion_aq2_03b9f006_identify
      - button.lumi_lumi_sensor_motion_aq2_283d5a07_identify
      - button.lumi_lumi_sensor_motion_aq2_f59c5f07_identify
      - button.lumi_lumi_sensor_wleak_aq1_d99dc207_identify
      - button.msl430_abdf_identify
      - button.msl430_b040_identify
      - button.philips_lct026_8ff58809_identify
      - button.sonoff_s26r2zb_0480c024_identify
      - button.sonoff_s26r2zb_8d7ec024_identify
      - button.sonoff_s26r2zb_bb7ec024_identify
      - button.velux_gateway_identify
      - button.velux_internal_cover_identify
      - button.velux_internal_cover_identify_2
      - button.velux_internal_cover_identify_3
      - button.velux_internal_cover_identify_4
      - button.velux_internal_cover_identify_5
      - button.velux_internal_cover_identify_6
      - button.velux_sensor_identify
      - button.velux_sensor_identify_2
      - binary_sensor.downstairs_bathroom_light_longpush_0
      - binary_sensor.downstairs_bathroom_light_longpush_1
      - binary_sensor.downstairs_bathroom_light_shortpush_0
      - binary_sensor.downstairs_bathroom_light_shortpush_1
      - binary_sensor.main_bedroom_lights_longpush_0
      - binary_sensor.main_bedroom_lights_longpush_1
      - binary_sensor.main_bedroom_lights_shortpush_0
      - binary_sensor.main_bedroom_lights_shortpush_1
      - button.upstairs_bathroom_light_restart
      - button.upstairs_bathroom_light_update_firmware
      - sensor.upstairs_bathroom_light_power_0
      - button.shelly_dimmer_2_e098069672cb_restart
      - button.upstairs_bathroom_motion_sensor_identify
      - sensor.upstairs_bathroom_motion_sensor_battery
      - sensor.upstairs_bathroom_motion_sensor_temperature
      - button.shelly_1l_3c6105e3579d_restart
      - button.shelly_1l_3c6105e391c1_restart
      - button.shelly_1l_e09806aa19a6_restart
      - button.shelly_1l_e8db84a1ad9e_restart
      - button.ewelink_ds01_f6569e23_identify
      - button.spare_room_light_restart
      - button.spare_room_light_update_firmware
      - sensor.spare_room_light_power_0
      - cover.curtains
      - scene.curtains_closed
      - scene.curtains_open
      - button.deebot_ozmo_920_lounge_relocate
      - button.deebot_ozmo_t8_aivi_kitchen_relocate
      - binary_sensor.shelly_motion_60a4239a615c_motion
      - binary_sensor.shelly_motion_60a4239a615c_vibration
      - sensor.shelly_motion_60a4239a615c_battery
      - sensor.shelly_motion_60a4239a615c_lux
      - cover.velux_internal_cover
      - cover.velux_internal_cover_2
      - cover.velux_internal_cover_4
      - cover.velux_internal_cover_6
      - sensor.velux_sensor_co2
      - sensor.velux_sensor_humidity
      - sensor.velux_sensor_temperature
      - cover.velux_internal_cover_3
      - cover.velux_internal_cover_5
      - binary_sensor.bedroom_1_light_longpush_0
      - binary_sensor.bedroom_1_light_longpush_1
      - binary_sensor.bedroom_1_light_shortpush_0
      - binary_sensor.bedroom_1_light_shortpush_1
      - binary_sensor.bedroom_2_light_longpush_0
      - binary_sensor.bedroom_2_light_longpush_1
      - binary_sensor.bedroom_2_light_shortpush_0
      - binary_sensor.bedroom_2_light_shortpush_1
      - binary_sensor.lounge_lights_longpush_0
      - binary_sensor.lounge_lights_longpush_1
      - binary_sensor.lounge_lights_shortpush_0
      - binary_sensor.lounge_lights_shortpush_1
      - binary_sensor.spare_room_light_longpush_0
      - binary_sensor.spare_room_light_longpush_1
      - binary_sensor.spare_room_light_shortpush_0
      - binary_sensor.spare_room_light_shortpush_1
      - binary_sensor.upstairs_bathroom_light_longpush_0
      - binary_sensor.upstairs_bathroom_light_longpush_1
      - binary_sensor.upstairs_bathroom_light_shortpush_0
      - binary_sensor.upstairs_bathroom_light_shortpush_1
      - sensor.spare_room_light_energy_0
      - sensor.upstairs_bathroom_light_energy_0
      - binary_sensor.front_floodlight_longpush_0
      - binary_sensor.front_floodlight_longpush_1
      - binary_sensor.front_floodlight_shortpush_0
      - binary_sensor.front_floodlight_shortpush_1
      - button.front_floodlight_restart
      - button.front_floodlight_update_firmware
      - sensor.front_floodlight_energy_0
      - sensor.front_floodlight_power_0
      - button.front_gate_contact_sensor_identify
      - binary_sensor.front_gate_contact_sensor_status
      - sensor.front_gate_contact_sensor_power
      - sensor.bedroom1_laptop_sessionstate
      - sensor.bedroom2_laptop_sessionstate
      - switch.bedroom1_laptop_hibernate
      - switch.bedroom1_laptop_restart
      - switch.bedroom1_laptop_shutdown
      - switch.bedroom2_laptop_hibernate
      - switch.bedroom2_laptop_restart
      - switch.bedroom2_laptop_shutdown
      - sensor.co2_intensity
      - sensor.grid_fossil_fuel_percentage
      - button.bedroom_1_bedside_lamp_identify
      - update.frigate_server
      - siren.hallway_siren
      - sensor.house_energy_total_consumption_cost
      - sensor.study_oil_radiator_energy_apparentpower
      - sensor.study_oil_radiator_energy_current
      - sensor.study_oil_radiator_energy_factor
      - sensor.study_oil_radiator_energy_power
      - sensor.study_oil_radiator_energy_reactivepower
      - sensor.study_oil_radiator_energy_today
      - sensor.study_oil_radiator_energy_total
      - sensor.study_oil_radiator_energy_totalstarttime
      - sensor.study_oil_radiator_energy_voltage
      - sensor.study_oil_radiator_energy_yesterday
      - sensor.gas_tariff_rate
      - sensor.gas_tariff_standing
      - sensor.gas_consumption_today_cost
      - sensor.electric_consumption_today
      - sensor.electric_consumption_year
      - sensor.electric_cost_today
      - sensor.electric_tariff_rate
      - sensor.front_pot_temperature
      - sensor.gas_consumption_today
      - sensor.gas_consumption_year
      - sensor.gas_cost_today
      - sensor.electric_tariff_standing
      - sensor.smart_meter_gas_power
      - button.downstairs_hall_smoke_alarm_identify
      - button.lumi_lumi_sensor_magnet_aq2_identify
      - sensor.dishwasher_duration
      - sensor.dishwasher_program_progress
      - sensor.dishwasher_remaining_program_time

binary_sensor:
  - platform: template
    sensors:
      unavailable_entities_alert:
        delay_on:
          minutes: 15 # delay before activating alert
        value_template: "{{ states('sensor.unavailable_entities')|int(0) > 0 }}"

automation:
  - id: ""
    alias: Unavailable Sensors
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.unavailable_entities_alert
    condition:
      condition: time
      after: "09:00:00"
      before: "00:00:00"
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: sensor.unavailable_entities
                    above: "0"
                  - condition: numeric_state
                    entity_id: sensor.unavailable_entities
                    below: "2"
            sequence:
              - service: notify.dad
                data:
                  title: There is {{ states('sensor.unavailable_entities')|int(0) }} device offline!
                  message:
                    "{{ state_attr('sensor.unavailable_entities','entities')
                    | join('

                    ') }}"
          - conditions:
              - condition: numeric_state
                entity_id: sensor.unavailable_entities
                above: "1"
            sequence:
              - service: notify.dad
                data:
                  title:
                    There are {{ states('sensor.unavailable_entities')|int(0) }} devices
                    offline!
                  message:
                    "{{ state_attr('sensor.unavailable_entities','entities')
                    | join('

                    ') }}"
        default:
          - service: notify.dad
            data:
              title: Attention!
              message: All devices are back online.
    mode: restart
