sensor:
  - platform: template
    sensors:
      unavailable_entities:
        friendly_name: Unavailable Entities
        unit_of_measurement: Entities
        icon_template: "{{ 'mdi:check-circle' if is_state('sensor.unavailable_entities','0') else 'mdi:alert-circle' }}"
        value_template: >
          {{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group')
            |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|list|count }}
        attribute_templates:
          entities: >
            {{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group')
              |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|map(attribute='entity_id')|join(',') }}
          names: >
            {{ states|selectattr('state','in',['unavailable','unknown','none'])|rejectattr('domain','eq','group')
              |rejectattr('entity_id','in',state_attr('group.ignored_entities','entity_id'))|map(attribute='name')|join(',') }}

group:
  ignored_entities:
    entities:
        - media_player.lg_webos_tv_d1bd
        - sensor.back_door_last_ding
        - binary_sensor.updater
        - sensor.blink_child2s_camera_temperature
        - sensor.blink_child2s_camera_wifi_signal
        - sensor.blink_child2s_camera_temperature_2
        - sensor.blink_child2s_camera_wifi_signal_2
        - sensor.dads_toothbrush
        - cover.bedroom
        - sensor.samsung_q60_series_lounge_media_playback_status
        - sensor.withings_body_temperature_c_child1
        - sensor.withings_bone_mass_kg_child1
        - sensor.withings_diastolic_blood_pressure_mmhg_child1
        - sensor.withings_fat_free_mass_kg_child1
        - sensor.withings_fat_mass_kg_child1
        - sensor.withings_fat_ratio_pct_child1
        - sensor.withings_heart_pulse_bpm_child1
        - sensor.withings_muscle_mass_kg_child1
        - sensor.withings_pulse_wave_velocity_child1
        - sensor.withings_skin_temperature_c_child1
        - sensor.withings_spo2_pct_child1
        - sensor.withings_systolic_blood_pressure_mmhg_child1
        - sensor.withings_temperature_c_child1
        - sensor.withings_weight_kg_child1
        - sensor.downstairs_bathroom_light_power_0
        - sensor.velux_sensor_current_temperature
        - sensor.downstairs_bathroom_motion_sensor_rssi
        - sensor.downstairs_bathroom_motion_sensor_ssid
        - sensor.downstairs_bathroom_motion_sensor_uptime
        - sensor.downstairs_bathroom_motion_sensor_ip
        - sensor.bedroom1_motion_sensor_rssi
        - sensor.bedroom1_motion_sensor_ssid
        - sensor.bedroom1_motion_sensor_uptime
        - sensor.bedroom1_motion_sensor_ip
        - binary_sensor.bedroom1_motion_sensor_charger
        - binary_sensor.downstairs_bathroom_motion_sensor_charger
        - sensor.deebot_ozmo_920_kitchen_last_clean_image
        - sensor.deebot_ozmo_920_kitchen_stats_area
        - sensor.deebot_ozmo_920_kitchen_stats_time
        - sensor.deebot_ozmo_920_kitchen_stats_type
        - sensor.deebot_ozmo_920_kitchen_water_level
        - sensor.deebot_ozmo_920_lounge_stats_area
        - sensor.deebot_ozmo_920_lounge_stats_time
        - sensor.deebot_ozmo_t8_aivi_kitchen_last_clean_image
        - sensor.deebot_ozmo_t8_aivi_kitchen_stats_area
        - sensor.deebot_ozmo_t8_aivi_kitchen_stats_time
        - sensor.deebot_ozmo_t8_aivi_kitchen_stats_type
        - sensor.deebot_ozmo_t8_aivi_kitchen_water_level
        - sensor.libby_ble
        - sensor.bedroom_1_light_energy_0
        - sensor.bedroom_1_light_power_0
        - sensor.bedroom_2_light_energy_0
        - sensor.bedroom_2_light_power_0
        - button.lounge_lights_update_firmware
        - button.main_bedroom_lights_update_firmware
        - sensor.downstairs_bathroom_light_power_0
        - sensor.downstairs_bathroom_light_energy_0
        - sensor.hottub_error
        - sensor.hottub_online
        - sensor.hottub_pump_target
        - sensor.hottub_pump_temp
        - sensor.hottub_status
        - sensor.hottub_summary
        - sensor.hottub_water_temp
        - switch.hottub_bubbles
        - switch.hottub_filter
        - switch.hottub_heat
        - switch.hottub_power
        - sensor.lounge_lights_overpower_value_0
        - sensor.main_bedroom_lights_energy_0
        - sensor.main_bedroom_lights_power_0
        - button.bedroom1_lights_update_firmware
        - button.bedroom2_lights_update_firmware
        - button.curtains_my_position
        - sensor.homekit_setup_code
        - button.downstairs_bathroom_lights_update_firmware
        - binary_sensor.shelly_motion_60a423936d7e_charger
        - binary_sensor.shelly_motion_60a423936d7e_firmware_update
        - binary_sensor.shelly_motion_60a423936d7e_motion
        - binary_sensor.shelly_motion_60a423936d7e_vibration
        - sensor.shelly_motion_60a423936d7e_battery
        - sensor.shelly_motion_60a423936d7e_lux

binary_sensor:
  - platform: template
    sensors:
      unavailable_entities_alert:
        delay_on:
          minutes: 15 # delay before activating alert
        value_template: "{{ states('sensor.unavailable_entities')|int > 0 }}"

automation:
- id: ''
  alias: Unavailable Sensors
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.unavailable_entities_alert
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: numeric_state
          entity_id: sensor.unavailable_entities
          above: '0'
        - condition: numeric_state
          entity_id: sensor.unavailable_entities
          below: '2'
      sequence:
      - service: notify.mobile_app_mobile_dad
        data:
          title: There is {{ states('sensor.unavailable_entities')|int }} device offline!
          message: '{{ state_attr(''sensor.unavailable_entities'',''names'').split('','')
            | join(''

            '') }}'
    - conditions:
      - condition: numeric_state
        entity_id: sensor.unavailable_entities
        above: '1'
      sequence:
      - service: notify.mobile_app_mobile_dad
        data:
          title: There are {{ states('sensor.unavailable_entities')|int }} devices
            offline!
          message: '{{ state_attr(''sensor.unavailable_entities'',''names'').split('','')
            | join(''

            '') }}'
    default:
    - service: notify.mobile_app_mobile_dad
      data:
        title: Attention!
        message: All devices are back online.
  mode: restart
