automation:
    - id: 'downstairs_bathroom_lights_on'
      alias: Downstairs Bathroom - Lights - On
      description: ''
      trigger:
      - type: motion
        platform: device
        device_id: 91625606098111eb8bbb11d32d5ba14c
        entity_id: binary_sensor.motion_sensor_motion
        domain: binary_sensor
      condition: []
      action:
      - type: turn_on
        device_id: 522f07ec0ed311eb8d90f54ebe9f79f4
        entity_id: switch.downstairs_bathroom_light
        domain: switch
      mode: single
    - id: 'downstairs_bathroom_lights_off'
      alias: Downstairs Bathroom - Lights - Off
      description: ''
      trigger:
      - type: no_motion
        platform: device
        device_id: 91625606098111eb8bbb11d32d5ba14c
        entity_id: binary_sensor.motion_sensor_motion
        domain: binary_sensor
        for:
          hours: 0
          minutes: 15
          seconds: 0
      condition: []
      action:
      - type: turn_off
        device_id: 522f07ec0ed311eb8d90f54ebe9f79f4
        entity_id: switch.downstairs_bathroom_light
        domain: switch
      mode: single
