automation:
    - id: 'downstairs_bathroom_lights_on'
      alias: Downstairs Bathroom - Lights - On
      description: ''
      trigger:
      - platform: state
        entity_id: binary_sensor.downstairs_bathroom_motion_sensor_motion
        from: 'off'
        to: 'on'
      condition: []
      action:
      - type: turn_on
        device_id: 522f07ec0ed311eb8d90f54ebe9f79f4
        entity_id: switch.downstairs_bathroom_light
        domain: switch
      mode: single
    - id: 'downstairs_bathroom_lights_off'
      alias: Downstairs Bathroom - Lights - Off
      description: ''
      trigger:
      - platform: state
        entity_id: binary_sensor.downstairs_bathroom_motion_sensor_motion
        from: 'on'
        to: 'off'
        for:
          hours: 0
          minutes: 5
          seconds: 0
      condition: []
      action:
      - type: turn_off
        device_id: 522f07ec0ed311eb8d90f54ebe9f79f4
        entity_id: switch.downstairs_bathroom_light
        domain: switch
      mode: single
