automation:
  - id: "Alarmo - Arm Night Mode"
    alias: Alarmo - Arm Night Mode
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_motion_sensor_composite_motion
        to: "off"
        for: 00:30:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: time
            after: "00:00:00"
            before: "06:00:00"
    action:
      - service: alarmo.arm
        data:
          entity_id: alarm_control_panel.alarmo
          mode: home
          force: true
    mode: single
  - id: "Alarmo - Disable Night Mode"
    alias: Alarmo - Disable Night Mode
    description: ""
    trigger:
      - platform: time
        at: "06:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
    action:
      - service: alarmo.disarm
        data:
          entity_id: alarm_control_panel.alarmo
    mode: single
