automation:
  alias: KLF reboot on hass stop event
  description: Reboots the KLF200 in order to avoid SSL Handshake issue
  trigger:
    - platform: homeassistant
      event: shutdown
  action:
    - service: velux.reboot_gateway
