automation:
  - id: "kitchen_vacuum_start"
    alias: Kitchen - Vacuum - Start Clean
    description: ""
    trigger:
      - platform: time
        at: "21:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: state
        entity_id: group.parents
        state: home
    action:
      - service: script.turn_on
        data:
          entity_id: script.vacuum_kitchen_start
    mode: single
