automation:
  - id: "internet_good_night"
    alias: House - Internet - Good Night
    description: ""
    trigger:
      - platform: time
        at: "20:00:00"
      - platform: state
        entity_id: group.people
        from: home
        to: not_home
    condition: []
    action:
      - service: switch.turn_off
        data: {}
        entity_id: switch.4g
    mode: single
