automation:
  - id: "bedroom2_pc_wake"
    alias: Bedroom 2 - Laptop - Wake
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.bedroom_2_laptop_options
        to: Wake
    condition: []
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: e4:5e:37:a9:b6:f4
      - delay: "2"
      - service: input_select.select_option
        data:
          option: None
        entity_id: input_select.bedroom_2_laptop_options
    mode: single
  - id: "bedroom2_pc_sleep"
    alias: Bedroom 2 - Laptop - Sleep
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.bedroom_2_laptop_options
        to: Sleep
      - platform: time
        at: "21:00:00"
    condition:
      - condition: state
        entity_id: "switch.bedroom2_laptop_hibernate"
        state: "unknown"
    action:
      - service: switch.toggle
        target:
          entity_id: switch.bedroom2_laptop_hibernate
      - delay: "2"
      - service: input_select.select_option
        data:
          option: None
        entity_id: input_select.bedroom_2_laptop_options
    mode: single
