automation:
    - id: 'spare_room_laptop_wake'
      alias: Spare Room - child1 Laptop - Wake
      description: ''
      trigger:
      - platform: state
        entity_id: input_select.child1_laptop_options
        to: Wake
      condition: []
      action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: 8c:ae:4c:e3:4b:d2
      - delay: '2'
      - service: input_select.select_option
        data:
          option: None
        entity_id: input_select.child1_laptop_options
      mode: single
    - id: 'spare_room_laptop_sleep'
      alias: Spare Room - child1 Laptop - Sleep
      description: ''
      trigger:
      - platform: state
        entity_id: input_select.child1_laptop_options
        to: Sleep
      - platform: time
        at: '21:00:00'
      condition: []
      action:
      - service: shell_command.sleep_child1_laptop
        data:
          option: None
      - delay: '2'
      - service: input_select.select_option
        data:
          option: None
        entity_id: input_select.child1_laptop_options
      mode: single
