automation:
  - id: "bedroom1_laptop_wake"
    alias: Bedroom1 - Laptop - Wake
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.bedroom_1_laptop_options
        to: Wake
    condition: []
    action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: 8c:ae:4c:e3:4b:d2
      - delay: "2"
      - service: input_select.select_option
        data:
          option: None
        entity_id: input_select.bedroom_1_laptop_options
    mode: single

  - id: "bedroom1_laptop_sleep"
    alias: Bedroom1 - Laptop - Sleep
    description: ""
    trigger:
      - platform: state
        entity_id: input_select.bedroom_1_laptop_options
        to: Sleep
      - platform: time
        at: "21:00:00"
    condition:
      - condition: state
        entity_id: "switch.bedroom1_laptop_hibernate"
        state: "unknown"
    action:
      - service: switch.toggle
        target:
          entity_id: switch.bedroom1_laptop_hibernate
      - delay: "2"
      - service: input_select.select_option
        data:
          option: None
        entity_id: input_select.bedroom_1_laptop_options
    mode: single
