automation:
  - id: "front_pot_moisture"
    alias: Front - Pot Moisture"
    description: ""
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.soil_moisture_1
        below: "15"
        for: "00:10:00"
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
    action:
      - service: notify.family
        data:
          message: Water the front pot, it's thirsty !
          data:
            sticky: "true"
