automation:
  - id: front_door_open
    alias: "Front door open"
    trigger:
      platform: state
      entity_id: binary_sensor.front_door_contact_sensor
      from: "off"
      to: "on"
      for:
        hours: 0
        minutes: 5
        seconds: 0
    condition:
      condition: numeric_state
      entity_id: sensor.outdoor_temperature
      below: 20
    action:
      - service: notify.family
        data:
          message: The front door is open, go check it
    mode: single
