automation:
  - id: front_gate_opened
    alias: "Front - Gate opened"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.front_gate_contact_sensor_status
      from: "off"
      to: "on"
    condition: []
    action:
      - service: notify.alexa_media
        data:
          target:
            - media_player.kitchen
            - media_player.lounge
            - media_player.mum_and_dad
          data:
            type: tts
          message: '<audio src="soundbank://soundlibrary/alarms/beeps_and_bloops/bell_02"/>'
  - id: front_gate_open
    alias: "Front - Gate open"
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.front_gate_contact_sensor_status
      from: "off"
      to: "on"
      for:
        hours: 0
        minutes: 2
        seconds: 0
    condition: []
    action:
      - service: notify.family
        data:
          message: The front gate is open, go check it
          data:
            sticky: "true"
