automation:
  - id: "calendar_holiday_on"
    alias: Calendar - Holiday On
    description: ""
    trigger:
      platform: state
      entity_id: calendar.vacation
      to: "on"
    condition: []
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.on_holiday
    mode: single
  - id: "calendar_holiday_off"
    alias: Calendar - Holiday Off
    description: ""
    trigger:
      platform: state
      entity_id: calendar.vacation
      to: "off"
    condition: []
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.on_holiday
    mode: single
