automation:
    - id: 'calendar_school_holiday_on'
      alias: Calendar - School Holiday On
      description: ''
      trigger:
        platform: state
        entity_id: calendar.school_holiday
        to: "on"
      condition: []
      action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.school_holidays
      mode: single
    - id: 'calendar_school_holiday_off'
      alias: Calendar - School Holiday Off
      description: ''
      trigger:
        platform: state
        entity_id: calendar.school_holiday
        to: "off"
      condition: []
      action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.school_holidays
      mode: single
