automation:
  - id: "downstairs_hall_good_morning"
    alias: Downstairs Hall - Good Morning
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.outdoor_illuminance
        below: 10000
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.downstairs_hall_lamp_level_light_color_on_off
    mode: single
  - id: "downstairs_hall_good_night"
    alias: Downstairs Hall - Good Night
    description: ""
    trigger:
      - platform: numeric_state
        entity_id: sensor.outdoor_illuminance
        above: 10000
    condition: []
    action:
      - service: light.turn_off
        target:
          entity_id:
            - light.downstairs_hall_lamp_level_light_color_on_off
    mode: single
