automation:
  - id: "downstairs_hall_good_morning"
    alias: Downstairs Hall - Good Morning
    description: ""
    trigger:
      - platform: time
        at: 06:00
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.downstairs_hall_lamp_level_light_color_on_off
    mode: single
