automation:
    - id: 'downstairs_hall_good_night'
      alias: Downstairs Hall - Good Night
      description: ''
      trigger:
      - platform: time
        at: 00:00
      condition:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      action:
      - service: switch.turn_off
        target:
          entity_id: 
            - switch.downstairs_hall_lamp
      mode: single
