automation:
  - id: "Mezzanine - Water Leak Notification"
    alias: "Mezzanine - Water Leak Notification"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.mezzanine_flood_sensor_flood
        from: "off"
        to: "on"
    action:
      service: notify.family
      data:
        title: "Belltower Water Leak !"
        message: "Have you left the sink running ?"
        data:
          push:
            sound:
              name: "default"
              critical: 1
              volume: 1.0
