automation:
    - id: 'front_garden_recycling_reminder'
      alias: Front - Recycling Reminder
      description: ''
      trigger:
      - platform: time
        at: 08:15
      condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: state
        entity_id: sensor.recycling_collection
        state: 0
        attribute: days
      action:
      - service: notify.family
        data:
          message: Reminder, its green bin day
      mode: single
    - id: 'front_garden_recycling_reminder_previous_day'
      alias: Front - Recycling Reminder Previous Day
      description: ''
      trigger:
      - platform: time
        at: '21:00'
      condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: state
        entity_id: sensor.recycling_collection
        state: 1
        attribute: days
      action:
      - service: notify.family
        data:
          message: Reminder, its green bin day tomorrow
      mode: single
