automation:
  - id: "front_garden_refuse_reminder"
    alias: Front - Garden Refuse Reminder
    description: ""
    mode: single
    trigger:
      - platform: time
        at: 08:15
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: state
        entity_id: sensor.garden_refuse_collection
        state: 0
        attribute: days
    action:
      - service: notify.family
        data:
          message: Reminder, its brown bin day
          data:
            sticky: "true"
  - id: "front_garden_refuse_reminder_previous_day"
    alias: Front - Garden Refuse Reminder Previous Day
    description: ""
    mode: single
    trigger:
      - platform: time
        at: "21:00"
    condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: state
        entity_id: sensor.garden_refuse_collection
        state: 1
        attribute: days
    action:
      - service: notify.family
        data:
          message: Reminder, its brown bin day tomorrow
          data:
            sticky: "true"
