automation:
  - id: "spare_room_energy_timed_saver_on"
    alias: Spare Room - Timed Energy Saver On
    description: ""
    trigger:
      - platform: time
        at: 06:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.energy_saver
            state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.spare_room_power_socket
    mode: single
  - id: "spare_room_energy_timed_saver_off"
    alias: Spare Room - Energy Saver Off
    description: ""
    trigger:
      - platform: time
        at: "00:00"
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.spare_room_power_socket
    mode: single
  - id: "spare_room_energy_saver_on"
    alias:  Spare Room - Energy Saver On
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.spare_room_motion_sensor_motion
        to: "on"
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.energy_saver
            state: "off"
          - condition: time
            after: "08:00:00"
            before: "22:00:00"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.spare_room_power_socket
    mode: single
  - id: "spare_room_power_energy_saver_off"
    alias: Spare Room - Energy Saver Off
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.spare_room_motion_sensor_motion
        to: "off"
        for: 00:30:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: time
            after: "08:00:00"
            before: "22:00:00"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.spare_room_power_socket
    mode: single