automation:
  - id: "lounge_energy_timed_saver_on"
    alias: Lounge - Timed Energy Saver on
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_motion_sensor_composite_motion
        to: "off"
        for: 00:30:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: time
            after: "00:00:00"
            before: "06:00:00"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.lounge_window_power_socket
            - switch.lounge_power_socket
            - switch.lounge_door_power_socket
    mode: single
  - id: "lounge_energy_timed_saver_off"
    alias: Lounge - Timed Energy Saver Off
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_motion_sensor_composite_motion
        to: "off"
        for: 00:30:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: time
            after: "00:00:00"
            before: "06:00:00"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.lounge_window_power_socket
            - switch.lounge_power_socket
            - switch.lounge_door_power_socket
    mode: single
  - id: "lounge_energy_saver_on"
    alias: Lounge - Energy Saver On
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_motion_sensor_composite_motion
        to: "on"
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.energy_saver
            state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.lounge_power_socket
            - switch.lounge_door_power_socket
    mode: single
  - id: "lounge_energy_saver_off"
    alias: Lounge - Energy Saver Off
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_motion_sensor_composite_motion
        to: "off"
        for: 00:30:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: time
            after: "09:00:00"
            before: "15:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.lounge_window_power_socket
            - switch.lounge_power_socket
            - switch.lounge_door_power_socket
    mode: single
