automation:
- alias: "Lounge - Window TV Button - Short"
  trigger:
    - platform: mqtt
      topic: "{{'shellies/shellybutton1-485519CA3460/input_event/0'}}"
  action:
    choose:
    - conditions:
        - condition: template
          value_template: '{{ trigger.payload_json.event == "S" }}'
      sequence: 
        service: switch.toggle
        target:
          entity_id: switch.lounge_window_power_socket
- alias: "Lounge - Window TV Button - Short"
  trigger:
    - platform: mqtt
      topic: "{{'shellies/shellybutton1-485519CA3460/input_event/0'}}"
  action:
    choose:
    - conditions:
        - condition: template
          value_template: '{{ trigger.payload_json.event == "L" }}'
      sequence: 
        service: light.toggle
        target:
          entity_id: light.front_floodlight