automation:
    - id: 'lounge_xbox_reminder'
      alias: Lounge - XBox Reminder
      description: ''
      trigger:
      - platform: state
        entity_id: binary_sensor.child2
        to: 'on'
      condition:
      - condition: state
        entity_id: input_boolean.on_holiday
        state: "off"
      - condition: time
        after: 05:00:00
        before: 09:00:00
      action:
      - service: notify.alexa_media
        data:
          message: child2, please close the lounge door so Mum and Dad can get some sleep
          data:
            type: tts
          target:
          - media_player.lounge
      mode: single
