automation:
    - id: 'child1_set_state_asleep'
      alias: child1 - Set  State Asleep
      description: ''
      trigger:
      - platform: state
        entity_id: timer.child1_awake
        to: idle
      condition: []
      action:
      - service: input_boolean.turn_on
        data: {}
        entity_id: input_boolean.child1_asleep
      mode: single
    - id: 'child1_set_state_awake'
      alias: child1 - Set State Awake
      description: ''
      trigger:
      - platform: state
        entity_id: binary_sensor.child1_noise_sensor
        to: 'on'
      - platform: state
        entity_id: binary_sensor.bedroom_1_motion_sensor_motion
        to: 'on'
      condition: []
      action:
      - service: input_boolean.turn_off
        data: {}
        entity_id: input_boolean.child1_asleep
      - service: timer.start
        data: {}
        entity_id: timer.child1_awake
      mode: single
    - id: 'child1_bedroom_noise_sensor_off'
      alias: child1 Bedroom - Noise Sensor - Off
      description: ''
      trigger:
      - platform: state
        entity_id: input_boolean.child1_noise_sensor_on
        from: 'on'
        to: 'off'
      condition: []
      action:
      - service: ffmpeg.stop
        data:
          entity_id: binary_sensor.ffmpeg_noise
      mode: single
    - id: 'child1_bedroom_noise_sensor_on'
      alias: child1 Bedroom - Noise Sensor - On
      description: ''
      trigger:
      - platform: state
        entity_id: input_boolean.child1_noise_sensor_on
        from: 'off'
        to: 'on'
      condition: []
      action:
      - service: ffmpeg.start
        data:
          entity_id: binary_sensor.ffmpeg_noise
      mode: single
    - id: 'child1_bedroom_noise_sensor_status'
      alias: child1 Bedroom - Noise Sensor Status
      description: ''
      trigger:
      - platform: state
        entity_id: binary_sensor.child1_noise_sensor
        to: unavailable
        for: 00:00:10
      condition: []
      action:
      - service: ffmpeg.restart
        data: {}
        entity_id: binary_sensor.child1_noise_sensor
      mode: single
