automation:
- id: kitchen_cupboard_motion_detected
  alias: "Kitchen Cupboard Motion Detected"
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_cupboard_motion_sensor_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: time
          weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    - condition: time
      after: '15:15:00'
      before: '18:00:00'
  action:
  - service: notify.family
    data:
      message: Snack attack, the snack pirates are in the cupboard
  mode: single
