automation:
  - id: "kitchen_energy_timed_saver_on"
    alias: Kitchen - Energy Timed Saver On
    description: ""
    trigger:
      - platform: time
        at: 06:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.kitchen_tv_power_socket
            - switch.kitchen_sky_power_socket
    mode: single
  - id: "kitchen_energy_timed_saver_off"
    alias: Kitchen - Energy Timed Saver Off
    description: ""
    trigger:
      - platform: time
        at: "00:00"
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.kitchen_tv_power_socket
            - switch.kitchen_sky_power_socket
    mode: single
  - id: "kitchen_energy_saver_on"
    alias: Kitchen - Energy Saver On
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion_sensor_composite_motion
        to: "off"
        for: 00:30:00
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "off"
    action:
      - service: script.turn_on
        target:
          entity_id:
            - script.kitchen_tv_off
    mode: single
  - id: "kitchen_energy_saver_off"
    alias: Kitchen - Energy Saver Off
    description: ""
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_motion_sensor_composite_motion
        to: "on"
    condition:
      - and:
          - condition: state
            entity_id: input_boolean.on_holiday
            state: "off"
          - condition: state
            entity_id: input_boolean.school_holidays
            state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.kitchen_tv_power_socket
            - switch.kitchen_sky_power_socket
    mode: single